###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Renata canseco ",
    "age": 13 ,
    "club": "River",
    "categoria": "c3",
    "email": "renatacasneco@gmail.com"
}


###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/66298d3491c1bc16dd8d18fe HTTP/1.1

###
PUT http://localhost:9000/api/users/66298d3491c1bc16dd8d18fe HTTP/1.1
Content-Type: application/json

{
    "name": "Martina Castillo 2",
    "age": "20",
    "club": "River",
    "categoria": "B3",
    "email": "martinacc@gmail.commm"
}

###
DELETE  http://localhost:9000/api/users/66304c6bdc3575f4ee35160e HTTP/1.1
